import * as MatchExtractor from "./extractors/MatchExtractor";

export async function GET() {
  const teamDatahome = {
    name: "Ali All-Stars",
    id: 1,
    pace: 100,
    player: [
      {
        id: 1,
        name: "Ali",
        age: 35,
        ratings: {
          diq: 54,
          dnk: 44,
          drb: 85,
          endu: 56,
          fg: 95,
          ft: 74,
          hgt: 85,
          ins: 64,
          jmp: 99,
          oiq: 65,
          pss: 93,
          reb: 94,
          spd: 34,
          stre: 94,
          tp: 58,
        },
        previouslyInjured: false,
        baller: 4223,
        sneakerz: 6567,
      },
      {
        id: 2,
        name: "George",
        age: 35,
        ratings: {
          diq: 54,
          dnk: 44,
          drb: 85,
          endu: 56,
          fg: 95,
          ft: 74,
          hgt: 85,
          ins: 64,
          jmp: 99,
          oiq: 65,
          pss: 93,
          reb: 94,
          spd: 34,
          stre: 94,
          tp: 58,
        },
        previouslyInjured: false,
        baller: 4223,
        sneakerz: 6567,
      },
      {
        id: 3,
        name: "Joe",
        age: 35,
        ratings: {
          diq: 54,
          dnk: 44,
          drb: 85,
          endu: 56,
          fg: 95,
          ft: 74,
          hgt: 85,
          ins: 64,
          jmp: 99,
          oiq: 65,
          pss: 93,
          reb: 94,
          spd: 34,
          stre: 94,
          tp: 58,
        },
        previouslyInjured: false,
        baller: 4223,
        sneakerz: 6567,
      },
    ],
    abbrev: "AAS",
    primaryColor: "#00FF55",
    secondaryColor: "FF3399",
  };

  const teamDataAway = {
    name: "Effigy All-Stars",
    id: 2,
    pace: 100,
    player: [
      {
        id: 4,
        name: "Pete",
        age: 35,
        ratings: {
          diq: 54,
          dnk: 44,
          drb: 85,
          endu: 56,
          fg: 95,
          ft: 74,
          hgt: 85,
          ins: 64,
          jmp: 99,
          oiq: 65,
          pss: 93,
          reb: 94,
          spd: 34,
          stre: 94,
          tp: 58,
        },
        previouslyInjured: false,
        baller: 4223,
        sneakerz: 6567,
      },
      {
        id: 5,
        name: "John",
        age: 35,
        ratings: {
          diq: 54,
          dnk: 44,
          drb: 85,
          endu: 56,
          fg: 95,
          ft: 74,
          hgt: 85,
          ins: 64,
          jmp: 99,
          oiq: 65,
          pss: 93,
          reb: 94,
          spd: 34,
          stre: 94,
          tp: 58,
        },
        previouslyInjured: false,
        baller: 4223,
        sneakerz: 6567,
      },
      {
        id: 6,
        name: "Mike",
        age: 35,
        ratings: {
          diq: 54,
          dnk: 44,
          drb: 85,
          endu: 56,
          fg: 95,
          ft: 74,
          hgt: 85,
          ins: 64,
          jmp: 99,
          oiq: 65,
          pss: 93,
          reb: 94,
          spd: 34,
          stre: 94,
          tp: 58,
        },
        previouslyInjured: false,
        baller: 4223,
        sneakerz: 6567,
      },
    ],
    abbrev: "EAS",
    primaryColor: "#FF0055",
    secondaryColor: "33FF99",
  };

  // const teamDataAway = importedTeams[1];
  const simulatedMatch = MatchExtractor.singleSimulation(
    teamDatahome,
    teamDataAway,
    { numPlayersOnCourt: 3 },
    new Date().getTime()
  );

  return Response.json({
    reports: simulatedMatch.reports.map((r) => ({
      event: r.event,
      time: r.time,
      text: r.text,
      score: r.currentScore,
    })),
  });
}
